# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER
# DOCKER_PASS
#

version: 2
jobs:
  build_deploy:
    machine:
      enable: true
    steps:
      - checkout
      - run: ./bin/build
      - run: ./bin/deploy
  integration_test:
    machine:
      enable: true
    steps:
      - checkout
      - run: make pytest

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - integration_test:
          filters:
            tags:
              only: /.*/
      - build_deploy:
          requires:
            - integration_test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
